chatai/urls.py
from django.urls import path
from . import views
app_name = "chatai"
urlpatterns = [
	path('',views.index, name="index"),
	path('register/',views.register, name='register'),
	path('<int:room_id>/room/',views.room,name="room"),
	path('<int:room_id>/login/',views.login,name="login"),
	path('<int:room_id>/verify/',views.verify,name="verify"),
	path('<int:room_id>/close/',views.close,name="close"),
	path('help/',views.help,name="help"),
	path('examples/',views.examples,name="examples"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
	path('chatai/', include('chatai.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views
'''
app_name = "polls"
urlpatterns = [
    # ex: /polls/
    path('', views.index, name='index'),
    # ex: /polls/5/
    path('<int:question_id>/', views.detail, name='detail'),
    # ex: /polls/5/results/
    path('<int:question_id>/results/', views.results, name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]
'''
app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

chatai/models.py
from django.db import models

class Utterance(models.Model):
	text = models.CharField(max_length=200)
	speaker_idx = models.IntegerField()
	send_time = models.DateTimeField(auto_now=True)
	self_eval = models.IntegerField(default=5,null=True,blank=True)
	def __str__(self):
		return ""

class Hit(models.Model):
	hit_number = models.IntegerField(unique=True)
	security_code = models.CharField(max_length=10)
	speaker_name = models.CharField(max_length=50,null=True,blank=True)
	listener_name = models.CharField(max_length=50,null=True,blank=True)
	hit_state = models.IntegerField(default=0)
	current_conv = models.IntegerField(null=True,blank=True)
	def __str__(self):
		return ""

class Conversation(models.Model):
	hit = models.ForeignKey(Hit,on_delete=models.CASCADE,null=True,blank=True)
	utterances = models.ManyToManyField(Utterance)
	speaker_name = models.CharField(max_length=50,null=True,blank=True)
	listener_name = models.CharField(max_length=50,null=True,blank=True)
	scene = models.CharField(max_length=10)
	emotion = models.CharField(max_length=5)
	context = models.CharField(max_length=200,null=True,blank=True)

	def __str__(self):
		return ""

chatai/views.py
from django.shortcuts import get_object_or_404,render,redirect
from django.http import HttpResponse,HttpResponseRedirect
from django.template import loader
from django.urls import reverse
from django.views import generic
from .models import Hit,Conversation,Utterance
import random
from .MyCommon import *
from .XmlFileCode import *
# Create your views here.
if not XmlCmd.isFileExist(MyCommon.glb_path):
    XmlCmd.createXml(MyCommon.glb_path)
    a=XmlCmd.writeXml(MyCommon.glb_path,["vacant_room","[1,2,3,4,5,6,7,8,9,10]"],"Hit","vacant_room")

def index(request):
    rep = render(request, 'chatai/index.html')
    if request.POST.get("room_id",False) and request.POST.get("room_id",False).isdigit():
        room_id = int(request.POST["room_id"])
        if room_id >0:
            rep = redirect(reverse("chatai:login",kwargs={"room_id":room_id}))
    return rep

def register(request):
    if not XmlCmd.isFileExist(MyCommon.glb_path):
        XmlCmd.createXml(MyCommon.glb_path)
        XmlCmd.writeXml(MyCommon.glb_path, ["vacant_room", "[1,2,3,4,5,6,7,8,9,10]"], "Hit", "vacant_room")
    vacant_room = XmlCmd.readXml(MyCommon.glb_path,"Hit","vacant_room")[1]
    cur_room = eval(vacant_room)
    new_hit_id =sorted(cur_room)[0]
    cur_room.remove(new_hit_id)
    XmlCmd.writeXml(MyCommon.glb_path, ["vacant_room", "["+",".join([str(item) for item in cur_room])+"]"], "Hit", "vacant_room")
    password = str(random.randint(0,10))+str(random.randint(0, 10))+str(random.randint(0, 10))+str(random.randint(0, 10))
    scene = MyCommon.glb_scene[random.randint(0,len(MyCommon.glb_scene)-1)]
    emotion = MyCommon.glb_emotion[random.randint(0,len(MyCommon.glb_emotion)-1)]
    hit = Hit(hit_number=new_hit_id, security_code=password)
    hit.save()
    conv = Conversation(scene=scene, emotion=emotion, hit=hit)
    conv.save()
    hit.current_conv = conv.pk
    hit.save()
    rep = render(request, 'chatai/register.html', {"new_hit_id": hit.hit_number, "password": hit.security_code})
    rep.set_cookie("login_room",str(new_hit_id),max_age=60*60)
    return rep

def room(request,room_id):
    hit = get_object_or_404(Hit, hit_number=room_id)
    conv = get_object_or_404(Conversation,pk=hit.current_conv)
    name = request.COOKIES.get("name", None)
    if int(request.COOKIES.get("login_room",-1))==room_id:
        print("房间号正确")
        print(hit.speaker_name is None,hit.listener_name,conv.context is None,conv.utterances)
        if hit.speaker_name is None:
            #rep = redirect(reverse("chatai:login", kwargs={"room_id": room_id}))
            #rep = redirect(reverse("chatai:room", kwargs={"hit": hit, "conv": conv, "room_id": room_id, "name": name}))
            rep = render(request, 'chatai/room.html', {"hit": hit, "conv": conv, "room_id": room_id, "name": name})
            print("speaker:",request.POST.get("speaker_name",False))
            if request.POST.get("speaker_name",False):
                print("修改speaker")
                name = request.POST.get("speaker_name",False)
                hit.speaker_name = request.POST["speaker_name"]
                hit.save()
                rep = redirect(reverse("chatai:room", kwargs={"room_id": room_id}))
                #rep = redirect(reverse("chatai:room", kwargs={"hit": hit, "conv": conv, "room_id": room_id, "name": name}))
                #rep = render(request, 'chatai/room.html', {"hit": hit, "conv": conv, "room_id": room_id, "name": name})
        elif hit.listener_name is None:
            print("保存listener_name")
            rep = render(request, 'chatai/room.html', {"hit": hit, "conv": conv, "room_id": room_id, "name": name})
            if request.POST.get("listener_name", False):
                print("保存listener_name",request.POST["listener_name"])
                name = request.POST.get("listener_name", False)
                hit.listener_name = request.POST["listener_name"]
                hit.save()
                rep = redirect(reverse("chatai:room", kwargs={"room_id": room_id}))
                #rep = redirect(reverse("chatai:room", kwargs={"hit": hit, "conv": conv, "room_id": room_id, "name": name}))
                #rep = render(request, 'chatai/room.html', {"hit": hit, "conv": conv, "room_id": room_id, "name": name})
        elif conv.context is None:
            if name==hit.speaker_name:
                print("进入阶段2：",request.POST.get("choice",False))
                if not request.POST.get("choice",False):
                    #rep = redirect(reverse("chatai:room", kwargs={"hit":hit,"conv":conv,"room_id":room_id,"name":name,'error_message':"You didn't select a choice."}))
                    rep = render(request, 'chatai/room.html',{"hit":hit,"conv":conv,"room_id":room_id,"name":name,'error_message':"You didn't select a choice."})
                elif request.POST.get("choice",False)=="0":
                    print("context文本:",request.POST.get("context",False))
                    if request.POST.get("context",False):
                        conv.context = request.POST["context"]
                        conv.save()
                        rep = redirect(reverse("chatai:room", kwargs={"room_id": room_id}))
                        #rep = redirect(reverse("chatai:room", kwargs={"hit": hit, "conv": conv, "room_id": room_id, "name": name,"cur_turn":0}))
                        #rep = render(request, 'chatai/room.html',{"hit": hit, "conv": conv, "room_id": room_id, "name": name,"cur_turn":0})
                    else:
                        #rep = redirect(reverse("chatai:room", kwargs={"hit": hit, "conv": conv, "room_id": room_id, "name": name,'error_message': "你选择创造场景但没有输入文本"}))
                        rep = render(request, 'chatai/room.html',{"hit": hit, "conv": conv, "room_id": room_id, "name": name,'error_message': "你选择创造场景但没有输入文本"})
                elif request.POST.get("choice",False)=="1":
                    conv.scene = MyCommon.glb_scene[random.randint(0, len(MyCommon.glb_scene) - 1)]
                    conv.emotion = MyCommon.glb_emotion[random.randint(0, len(MyCommon.glb_emotion) - 1)]
                    conv.save()
                    rep = redirect(reverse("chatai:room", kwargs={"room_id": room_id}))
                    #rep = redirect(reverse("chatai:room", kwargs={"hit": hit, "conv": conv, "room_id": room_id, "name": name}))
                    #rep = render(request, 'chatai/room.html', {"hit": hit, "conv": conv, "room_id": room_id, "name": name})
            else:
                print("打印",hit.listener_name is None ,hit.speaker_name,name)
                #rep = redirect(reverse("chatai:room", kwargs={"room_id": room_id}))
                #rep = redirect(reverse("chatai:room", kwargs={"hit": hit, "conv": conv, "room_id": room_id, "name": name}))
                rep = render(request, 'chatai/room.html', {"hit": hit, "conv": conv, "room_id": room_id, "name": name})
        elif name in [hit.speaker_name,hit.listener_name]:
            if conv.utterances.count()==0:
                cur_turn = 0
            else:
                cur_turn = int(1-conv.utterances.latest("send_time").speaker_idx)
            if request.POST.get("speaker_text",False) and cur_turn==0:
                u = Utterance(text=request.POST["speaker_text"],speaker_idx=0)
                u.save()
                conv.utterances.add(u)
                conv.save()
                rep = redirect(reverse("chatai:room", kwargs={"room_id": room_id}))
                #rep = redirect(reverse("chatai:room",kwargs={"hit": hit, "conv": conv, "room_id": room_id, "name": name,"history":conv.utterances.order_by("send_time"),"cur_turn":int(1-cur_turn),"length":conv.utterances.count()}))
                #rep = render(request, 'chatai/room.html', {"hit": hit, "conv": conv, "room_id": room_id, "name": name,"history":conv.utterances.order_by("send_time"),"cur_turn":int(1-cur_turn),"length":conv.utterances.count()})
            elif request.POST.get("listener_text",False) and  cur_turn==1:
                u = Utterance(text=request.POST["listener_text"],speaker_idx=1)
                u.save()
                conv.utterances.add(u)
                conv.save()
                rep = redirect(reverse("chatai:room", kwargs={"room_id": room_id}))
                #rep = redirect(reverse("chatai:room", kwargs={"hit": hit, "conv": conv, "room_id": room_id, "name": name,"history":conv.utterances.order_by("send_time"),"cur_turn":int(1-cur_turn),"length":conv.utterances.count()}))
                #rep = render(request, 'chatai/room.html', {"hit": hit, "conv": conv, "room_id": room_id, "name": name,"history":conv.utterances.order_by("send_time"),"cur_turn":int(1-cur_turn),"length":conv.utterances.count()})
            else:
                #rep = redirect(reverse("chatai:room", kwargs={"hit": hit, "conv": conv, "room_id": room_id, "name": name,"history":conv.utterances.order_by("send_time"),"cur_turn":cur_turn,"length":conv.utterances.count()}))
                rep = render(request, 'chatai/room.html', {"hit": hit, "conv": conv, "room_id": room_id, "name": name,"history":conv.utterances.order_by("send_time"),"cur_turn":cur_turn,"length":conv.utterances.count()})
        else:
            rep = redirect(reverse("chatai:login", kwargs={"room_id": room_id}))
    else:
        rep = redirect(reverse("chatai:login",kwargs={"room_id":room_id}))
    rep.set_cookie("name", name, max_age=60 * 60)
    rep.set_cookie("login_room", room_id, max_age=60 * 60)
    return rep

def login(request,room_id):
    return render(request,'chatai/login.html',{"room_id":room_id})

def verify(request,room_id):
    hit = get_object_or_404(Hit, hit_number=room_id)
    if request.POST.get("password","") == hit.security_code:
        rep = redirect(reverse("chatai:room",kwargs={"room_id":room_id}))
        print("login_room",room_id)
        rep.set_cookie("login_room", str(room_id), max_age=60 * 60)
        print("name",request.POST.get("name", ""))
        rep.set_cookie("name", request.POST.get("name", ""), max_age=60 * 60)
    else:

chatai/templates/chatai/close.html
<p>{{result}}</p>

chatai/templates/chatai/examples.html
<p>haha</p>

chatai/templates/chatai/help.html
<h1>帮助手册</h1>
<p><a href="https://docs.qq.com/doc/DYVdmQmFOYVF0a1VG?pub=1&dver=2.1.0" target="_blank">我们是要做什么？---志愿者必读</a></p>

chatai/templates/chatai/index.html
<h1>帮助手册a</h1>
<p><a href="https://docs.qq.com/doc/DYVdmQmFOYVF0a1VG?pub=1&dver=2.1.0" target="_blank">我们是要做什么？---志愿者必读</a></p>
<h1>开始</h1>
<p>感谢您志愿参与中文共情对话数据集构造工作！</p>
<p>您首先要选择进入房间或者创建房间。您进入每个房内会看到一个对话任务，一个房间只会有两个人能进入。</p>
<p>新房创建成功后，您会得到一个房间号和房间密码（务必记住）。掉线的用户可以凭密码重新进入房间。</p>
<p>----------------------------------------------------------------------------------</p>
<p><a href="/chatai/register/">创建新房间</a></p>
<form action="{% url 'chatai:index' %}" method="post">
    {% csrf_token %}
    已有房间号：
    <input type="text" name="room_id" style="width:50px"/>
    <input type="submit" value="房进入间" />
</form>

chatai/templates/chatai/login.html
<p>请登录房间</p>
<form action="{% url 'chatai:verify' room_id %}" method="post">
    {% csrf_token %}
    <p>{{room_id}}号房间密码：<input type="text" name="password" /></p>
    <p>你的名字：<input type="text" name="name" /></p>
    <p><input type="submit" value="进入" /></p>
</form>

chatai/templates/chatai/register.html
<p><strong>请记住并保存这些信息</strong></p>
    <p>对话号：<b>{{new_hit_id}}</b>，房间密码：<b>{{password}}</b></p>
<p><a href="/chatai/{{new_hit_id}}/room/">进入房间</a></p>

chatai/templates/chatai/room.html
{% load staticfiles %}
{% if hit.speaker_name is None %}
    <form action="{% url 'chatai:room' room_id %}" method="post">
        {% csrf_token %}
        <p>等待speaker签名：<input type="text" name="speaker_name" /></p>
        <p>推荐用复杂的英文，目前系统很傻，需要您保证不会撞名字</p>
        <p><input type="submit" value="下一步listner签名" /></p>
    </form>
{%elif hit.listener_name is None %}
        {% if hit.speaker_name != name %}
        <form action="{% url 'chatai:room' room_id %}" method="post">
            {% csrf_token %}
            <p>如果你已经成为speaker，请不要提交。请找另一个listner进入房间签名。</p>
            <p>等待listener签名<input type="text" name="listener_name" /></p>
            <p>推荐用复杂的英文，目前系统很傻，需要您保证不会撞名字</p>
            <p><input type="submit" value="下一步创造场景" /></p>
        </form>
        {%else%}
        <p>你已经成为speaker。请复制链接邀请另一个listner进入房间签名。</p>
        <script language="JavaScript">setTimeout(function(){location.reload()},20000);</script>
        {%endif%}
{%elif conv.context is None %}
        {% if hit.speaker_name == name%}
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        <p>主题：{{conv.scene}}</p>
        <p>情绪：{{conv.emotion}}</p>
        <form action="{% url 'chatai:room' room_id %}" method="post">
            {% csrf_token %}
            <p>作为speaker，您需要根据主题和情绪，且基于<b>真实经历</b>，创造一个场景。如果这个主题和情绪搭配下，您没有过真实经历，可选择换一组搭配。</p>
            <p><input type="radio" name="choice" id="choice1" value="0">创造场景:<input type="text" name="context" style="width:1000px;"/></p>
            <p><input type="radio" name="choice" id="choice2" value="1">换一组搭配</p>
            <p><input type="submit" value="提交" /></p>
        </form>
        <p>---------------------------------------备忘--------------------------------------------</p>
        <p><strong>场景构造</strong></p>
        <img src="{% static 'chatai/speakerDuty1.png' %}" width="400" height="100"/>
        <p><strong>事件解释</strong></p>
        <img src="{% static 'chatai/introForEvents.png' %}" width="500" height="300"/>
        <p><a href="https://docs.qq.com/doc/DYVdmQmFOYVF0a1VG?pub=1&dver=2.1.0" target="_blank">帮助手册---志愿者必读</a></p>
        {%else%}
        <p>speaker正在创造场景，请等待，完成后再刷新会出现对话页面。</p>
        <script language="JavaScript">setTimeout(function(){location.reload()},5000);</script>
        <form action="{% url 'chatai:room' room_id %}" method="post">{% csrf_token %}<input type="submit" value="刷新" /></form>
        {%endif%}
{%elif cur_turn == 0 %}
        <p>----------------------------------历史对话----------------------------------------</p>
        {% if history is not None %}
        {% for item in history %}
            <li>{{item.text}}</li>
        {% endfor %}
        {% endif %}
        {% if hit.speaker_name == name %}
        <p>-----------------------------任务设定（仅speaker可见）----------------------------</p>
        <p>主题：{{conv.scene}}</p>
        <p>情绪：{{conv.emotion}}</p>
        <p>情景：{{conv.context}}</p>
        <p>-------------------------------------设置回复-------------------------------------</p>
        <p>规则：第一句由speaker开始，最后一句由listener说出。如果speaker觉得对话可以结束了，停止回复，并按下结束按钮。对话不少于10句，不多于20句。</p>
        {% if length is not None %}
        <p>
            {% if length > 9 %}
            <form action="{% url 'chatai:close' room_id %}" method="post">
                {% csrf_token %}
                当前对话长度：<strong>{{length}}</strong>句。
                <input type="hidden" name="close" value="1">
                <input type="submit" value="结束对话" />
            </form>
            {%endif%}
        </p>
        {% endif %}
        <form action="{% url 'chatai:room' room_id %}" method="post">
            {% csrf_token %}
            <p>speaker发言：<input type="text" name="speaker_text" style="width:1000px;" /></p>
            <p><input type="submit" value="提交" /></p>
        </form>
        <p>---------------------------------------备忘--------------------------------------------</p>
        <p><strong>说话人义务</strong></p>
        <img src="{% static 'chatai/speakerDuty2.png' %}" width="500" height="150"/>
        <p><a href="https://docs.qq.com/doc/DYVdmQmFOYVF0a1VG?pub=1&dver=2.1.0" target="_blank">帮助手册---志愿者必读</a></p>
        {%else%}
        <p>等待speaker说话...过会再来刷新吧~</p>
        <script language="JavaScript">setTimeout(function(){location.reload()},5000);</script>
        <form action="{% url 'chatai:room' room_id %}" method="post">{% csrf_token %}<input type="submit" value="刷新" /></form>
        {%endif%}


{%elif cur_turn == 1 %}
        <p>----------------------------------历史对话----------------------------------------</p>
        {% if history is not None %}
        {% for item in history %}
            <li>{{item.text}}</li>
        {% endfor %}
        {% endif %}
        {% if hit.listener_name == name %}
        <p>-------------------------------------设置回复-------------------------------------</p>
        <form action="{% url 'chatai:room' room_id %}" method="post">
            {% csrf_token %}
            <p>规则：第一句由speaker开始，最后一句由listener说出。如果speaker觉得对话可以结束了，停止回复，并按下结束按钮。对话不少于10句，不多于20句。</p>
            {% if length is not None %}
            <p>当前对话长度：<strong>{{length}}</strong>句</p>
            {% endif %}
            <p>listener发言：<input type="text" name="listener_text" /></p>
            <p><input type="submit" value="提交" /></p></form>
        <p>---------------------------------------备忘--------------------------------------------</p>
        <p><strong>回复技巧</strong></p>
        <img src="{% static 'chatai/repStyle.png' %}" width="500" height="600"/>
        <p><a href="https://docs.qq.com/doc/DYVdmQmFOYVF0a1VG?pub=1&dver=2.1.0" target="_blank">帮助手册---志愿者必读</a></p>
        {%else%}
        <p>等待listener说话...过会再来刷新吧~</p>
        <script language="JavaScript">setTimeout(function(){location.reload()},5000);</script>
        <form action="{% url 'chatai:room' room_id %}" method="post">{% csrf_token %}<input type="submit" value="刷新" /></form>
        {%endif%}


{%else%}
{%endif%}